---
driver:
  name: vagrant

provisioner:
  attributes:
    citadel:
      access_key_id: <%= ENV['BALANCED_AWS_ACCESS_KEY_ID'] || ENV['AWS_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['BALANCED_AWS_SECRET_ACCESS_KEY'] || ENV['AWS_SECRET_ACCESS_KEY'] %>

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]

suites:
- name: server
  run_list:
  - recipe[balanced-ci::server]
  driver:
    customize:
      memory: 2048
      cpus: 2
    network:
    - [private_network, {ip: 10.2.3.4}]
  attributes:
    jenkins:
      server:
        nodes:
          builder-ubuntu-1204:
            labels: [cookbooks, balanced, rump, brache, billy, balanced-docs, precog]
            path: /srv/ci

- name: builder
  run_list:
  - recipe[balanced-ci::cookbooks]
  driver:
    vm_hostname: builder
  attributes:
    ci:
      server_url: http://10.2.3.4:8080/
